version: '3.8' 
 
services: 
  mqtt: 
    image: eclipse-mosquitto 
    container_name: mqtt_brocker 
    ports: 
      - "1883:1883" # TCP 
    volumes: 
      - ./mosquitto/config:/mosquitto/config 
      - ./mosquitto/data:/mosquitto/data 
      - ./mosquitto/log:/mosquitto/log 
    restart: unless-stopped 